### ISSUE TITLE
A outcry of Logcat for Pix3lify module.

### ISSUE THREAD

**Issue by PranavBhattrai** [Magisk-Modules-Repo/op5camlibfix#1]
Please. Pix3lify is great module to have pixel features. If a developer is reading this and owns a OnePlus 5 device, please flash Pix3lify module and send the Logcat to them. They will resolve the issue. I hope u know what"Logcat" is! I want to do this but don't know how. 🙂

**Comment by nipunnarang** [comment]
This has nothing to do with this Magisk module.
