### ISSUE TITLE
Useful with LineageOS? 

### ISSUE THREAD

**Issue by SuperITMan** [Magisk-Modules-Repo/op5camlibfix#3]
Hello,

I was looking for good apps on Magisk for my OP5 with rooted LineageOS and I saw your fix lib.

I would like to know if it is useful for LineageOS.

Because, I'm using the OnePlus Camera application and the smile detection to take selfie is not working :disappointed:

Do you think your app could solve this? :blush:

Thanks for your app in any case.

Regards,
Alexis

**Comment by nipunnarang** [comment]
The fix won't solve any issue that you're having with the stock camera. It's for adding Google Camera Mod compatibility to stock as well as custom OP5 ROMs. Please read the README.md for more details.
